
# default.yaml
# Default voice profile

# sequences in the form [x, x, x] denote [setValue, sliderMinimum, sliderMaximum]

version: 0x04

# wavetable selections
OscWaveSelector1: 2
OscWaveSelector2: 3

# Frequency parameters
MasterPitchOffset:
  Octave: [0, -5, 5]
  Semitone: [0, -12, 12]
  Pitch: [0, -100, 100]
Osc1PitchOffset:
  Octave: [0, -5, 5]
  Semitone: [0, -12, 12]
  Pitch: [1.34, -100, 100]
Osc2PitchOffset:
  Octave: [1, -5, 5]
  Semitone: [0, -12, 12]
  Pitch: [12.86, -100, 100]
Osc3PitchOffset:
  Octave: [1, -5, 5]
  Semitone: [7, -12, 12]
  Pitch: [-8.79, -100, 100]

# Envelope generator parameters
Osc1Volume:
  Depth: [1, 0, 10]
  Attack: [0.05, 0, 2]
  Decay: [0.2, 0, 2]
  Sustain: [0.7, 0, 1]
  Release: [0.2, 0, 2]
FilterCutoff:
  Depth: [4, 0, 8]
  Attack: [0.05, 0, 2]
  Decay: [0.2, 0, 2]
  Sustain: [0.2, 0, 1]
  Release: [0.25, 0, 2]
FilterResonance:
  Depth: [3, 0, 8]
  Attack: [0.05, 0, 2]
  Decay: [0.2, 0, 2]
  Sustain: [0.5, 0, 1]
  Release: [0.3, 0, 2]
